### ISSUE TITLE
About pututu

### ISSUE THREAD

**Issue by sjkyspa** [uport-project/lambda-fatima#20]
where is the pututu service?

**Comment by KamesCG** [comment]
@sjkyspa The pututu service is currently a "centralized" uPort service that is used to create push notifications to uPort Applications via the `pushToken`.  The `pushToken` is sent when the `notifications` parameter is set to `true` during `credentialRequest` URL encoding.

@ajunge or @c-castillo will be able to provide more in-depth details and timeline for Open Sourcing the project.

**Comment by ajunge** [comment]
Depends on https://github.com/uport-project/infrastructure/issues/8

**Comment by sjkyspa** [comment]
@ajunge  Ok, thanks. I will close this
